version: '3'
services:
  unifi-protect:
    container_name: unifi-unvr
    privileged: true
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/storage/srv:/srv'
      - '/storage/data:/data'
      - '/storage/persistent:/persistent'
    network_mode: 'host'
    restart: unless-stopped
    image: 'snowsnoot/unifi-unvr:latest'

